version: '3'
services:

  book-catalog:
    image: book-catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DATABASE_URL=postgresql://project_part3_pi7h_user:GZoIDCAih6W6ixNrVrlUSmceOBctbTo7@dpg-crmla1i3esus73fvaut0-a.oregon-postgres.render.com/project_part3_pi7h
    restart: "no"

  inventory-management:
    image: inventory-management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
     - "8082:8082"
    environment:
      - PORT=8082
      - DATABASE_URL=postgresql://project_part3_pi7h_user:GZoIDCAih6W6ixNrVrlUSmceOBctbTo7@dpg-crmla1i3esus73fvaut0-a.oregon-postgres.render.com/project_part3_pi7h
    restart: "no"